# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1 - 

#a) En ese caso el sistema tiene solucion y es unica
#b) En este caso p = 0.
#c)En esta caso hay que analizar (1) pues (I-A) no es inversible. Nos queda el sistema (I-A) p = d como (I-A) no es inversible entonces el sistema no tiene solucion o tiene infinitas soluciones.
#d) En este caso tenemos el siguiente sistema homogeno (I-A) = 0, como (I-A) es homogoneo entonces el sistema tiene infinitas soluciones.

### Consigna 2 -  

In [1]:
import numpy as np
from funciones import *

In [ ]:
### Consigna 3 -

In [40]:
A = np.array([[0.3,0,0.1],[0.05,1.0,0.2],[0.1,0.15,0.1]])
d = np.array([100,100,300])
ML = np.eye(np.shape(A)[0]) - A

#calculamos L, U, P y la inversa de ML:
L, U, P = calcularLU(ML)
ML_inv = inversaLU(L,U,P)

#calculamos p:
p = ML_inv @ d
print(f'p = \n {p}')

esto es n---> 3
Pivote 1 es nulo
[(-0.15, 2)]
L despues de permutar 
 [[ 1.          0.          0.        ]
 [-0.14285714  1.          0.        ]
 [-0.07142857  0.          1.        ]]
(3, 3)
p = 
 [   68.96551724 -5149.42528736  -517.24137931]


In [ ]:
### Consigna 4 - 

In [7]:
### Consigna 5

Z = np.array([[350,0,0],[50,250,150],[200,150,550]])
P_inv = np.array([[1/1000,0,0],[0,1/500,0],[0,0,1/1000]]) #P_inv_ij = 1/(P_ij), ya que P es una matriz diagonal.

A = Z @ P
print(f'A =\n {A}')

#Ahora calculamos la matriz de Leontief. (L = (I-A)_inv)

ImenosA = np.eye(3) - A
L, U, P = calcularLU(ImenosA)

ML = inversaLU(L,U,P)

print(f'Matriz de Leontief:\n {ML}')

#print(ImenosA @ ML) para chequear que vale.


A =
 [[350.   0.   0.]
 [ 50. 250. 150.]
 [200. 150. 550.]]
esto es n---> 3
(3, 3)
Matriz de Leontief:
 [[-2.86532951e-03  0.00000000e+00  0.00000000e+00]
 [-6.39800900e-05 -4.80731342e-03  1.31347361e-03]
 [ 1.06131679e-03  1.31347361e-03 -2.18036620e-03]]
