# Trabajo Práctico 1 - Matrices de Insumo Producto

## Enunciado

### Consigna 1 - 

1. En ese caso el sistema tiene solución y es única.
2. En este caso  __p__ = 0 \.
3. En este caso hay que analizar (__1__) pues (__I-A__) no es inversible. Nos queda el sistema (__I-A__) __p__ = __d__ . Como (__I-A__) no es inversible, entonces el sistema no tiene solución o tiene infinitas soluciones.
4. En este caso tenemos el siguiente sistema homogéneo (__I-A__) __p__ = 0 . Como tenemos un homogéneo e (__I-A__) no es inversible , entonces el sistema tiene infinitas soluciones.

### Consigna 2 -  

In [73]:
import numpy as np
from funciones import *

### Consigna 3 -

In [75]:
A = np.array([[0.3,0,0.1],[0.05,1.0,0.2],[0.1,0.15,0.1]])
d = np.array([100,100,300])
ML = np.eye(np.shape(A)[0]) - A

#calculamos L, U, P y la inversa de ML:
L, U, P = calcularLU(ML)
ML_inv = inversaLU(L,U,P)

#calculamos p:
p = ML_inv @ d
print(f'p = \n {p}')

esto es n---> 3
Pivote 1 es nulo
[(-0.15, 2)]
L despues de permutar 
 [[ 1.          0.          0.        ]
 [-0.14285714  1.          0.        ]
 [-0.07142857  0.          1.        ]]
(3, 3)
p = 
 [   68.96551724 -5149.42528736  -517.24137931]


### Consigna 4 - 

Primero escribimos **(2)** con **p'** y **d'**.

$$
\mathbf{p}' = (I - A)^{-1} \mathbf{d}'
$$

$$
\mathbf{p}' = (I - A)^{-1} \left( \begin{bmatrix} d_1 \\ d_2 \\ d_3 \end{bmatrix} + \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix} \right)
$$

Si distribuimos la matriz de **Leontief** nos queda:

$$
\mathbf{p}' = \mathbf{p} + (I - A)^{-1}  \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
$$

Luego...

$$
\Delta p = \mathbf{p}' - \mathbf{p}
$$

Finalmente:

$$
\Delta p = (I - A)^{-1} \Delta d
$$

### Consigna 5 - 

* Escribimos los datos del problema:

In [88]:

Z = np.array([[350,0,0],[50,250,150],[200,150,550]])
P_inv = np.array([[1/1000,0,0],[0,1/500,0],[0,0,1/1000]]) #P_inv_ij = 1/(P_ij), ya que P es una matriz diagonal.


* Calculamos los coeficientes tecnicos de la matriz **A**:

In [83]:
A = Z @ P_inv
print(f'A = \n {A}')

A = 
 [[0.35 0.   0.  ]
 [0.05 0.5  0.15]
 [0.2  0.3  0.55]]


* Ahora calculamos la matriz de Leontief:

In [90]:
ImenosA = np.eye(3) - A
L, U, P = calcularLU(ImenosA)

ML = inversaLU(L,U,P)

print(f'Matriz de Leontief:\n {ML}')

#print(ImenosA @ ML) para chequear que vale.

esto es n---> 3
(3, 3)
Matriz de Leontief:
 [[1.53846154 0.         0.        ]
 [0.44871795 2.5        0.83333333]
 [0.98290598 1.66666667 2.77777778]]


### Consigna 6

### Consigna 7

In [ ]:
import pandas as pd